### PR TITLE
Filtering part1

### PR DESCRIPTION
**Pull request by NatiSeifu**
refers to issue #4, filtering works pretty well, some things to discuss about in the meeting next week

### CODE REVIEW

**Comment by hebronmekuria** [comment]
Nice! I think you should hide your API key in a .env file tho to avoid it appearing on github, since this is a public repo

**Comment by NatiSeifu** [comment]
> Nice! I think you should hide your API key in a .env file tho to avoid it appearing on github, since this is a public repo

It is in an env file, read the commits : )

**Comment by hebronmekuria** [comment]
I see, I see, idk why it's still showing the APIKEY then, I need to do more research on how gitignore works.

**Comment by NatiSeifu** [comment]
API_KEY is just the variable I gave the _actual_ API key in the env file that is hidden

**Comment by hebronmekuria** [comment]
Screenshot 2024-06-08 at 10 10 55 AM
WAit so why does it show me an API key here

**Comment by NatiSeifu** [comment]
Oh it’s in red, so it means it was removed. I had it in the initial commit

Natnael "Nati" Seifu
Biology and Neuroscience Graduate
Phone Number: *571-412-8478*

**Pull request merged**
